# SO
alias reswp="sudo swapoff --all && sudo swapon /dev/sda2 --all"

# PYTHON
alias rmpycache="find . | grep -E \"(__pycache__|\.pyc|\.pyo$)\" | xargs rm -rf"

# DOCKER
alias dcstop="docker stop \$(docker ps -q)"
alias dcps="docker ps"
alias dcrm="docker rm -f \$(docker ps -aq) || true"
alias dcrmi="docker rmi -f \$(docker images -q) || true"
alias dcrmall="dcrm && dcrmi && docker volume prune -f \
    ┆   ┆   ┆  &&  docker network prune -f" 
